<div class="warranty_main_heading">
	<div class="container">
		<h1>Warranty Register</h1>
	</div>
</div>
<div class="warranty_section2">
	<div class="container">
		<h1>Warranty Register</h1>
		<p>To take advantage of the VersaDesk Warranty simply fill out the form below to complete your registration.</p>
		<p>After you submit the form, you will receive an email asking for opt in to our list. You will need to select yes in order to complete the registration process.</p>
		<img src="images/warranty.png" />
		<div class="warranty-registration-form">
			<div class="form-inner-part">
				<form id="warranty-reg-form" action="" method="post">
					<div class="form-view-fields">
					<div class="form-background-top-line"></div>
						<div class="form-fields-part">
							<div class="form-top-part">
								<div class="warranty-form-title-row">
									<div class="warranty-form-top-title">Warranty Registration</div>
								</div>
								<div class="warranty-form-header-description">VersaDesk Warranty Registration</div>
								<div class="form-required-warning">* Required</div>
							</div>
							<div class="form-middle-part">
								<div class="form-field">
									<div class="form-field-title">Email address <span class="required-warn">*</span></div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="email" required="" type="text" placeholder="Your email" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">First Name</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="first_name" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">Last Name</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="last_name" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">Email address</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="email" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">Address</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="address" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">Address Line 2</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="address2" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">City</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="city" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">State/ Province/ Region</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="state" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">Postal/ Zip Code</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="zip_code" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">Country</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="country" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">Order Number</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="order_number" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-field-title">Serial Code</div>
									<div class="form-main-field">
										<div class="form-field-inside"><input class="form-input-field" name="seriol_code" required="" type="text" placeholder="Your answer" /></div>
									</div>
								</div>
								<div class="form-field">
									<div class="form-submit field"><button>Submit</button></div>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<style xml="space">
.warranty-registration-form {
	font-family: Roboto,RobotoDraft,Helvetica,Arial,sans-serif;
	color: rgba(0,0,0,.87);
}
.warranty-registration-form .form-inner-part {
    margin: auto;
    width: 640px;
    max-width: 100%;
}
.warranty-registration-form .form-view-fields {
    padding-bottom: 0;
    -webkit-border-radius: 6px;
    border-radius: 6px;
    margin-bottom: 6px;
    background-color: #fff;
    -webkit-box-shadow: 0 1px 4px 0 rgba(0,0,0,0.37);
    box-shadow: 0 1px 4px 0 rgba(0,0,0,0.37);
    word-wrap: break-word;
    margin-top: 50px;
}
.warranty-registration-form .form-background-top-line {
    border-top-left-radius: 6px;
    border-top-right-radius: 6px;
    height: 8px;
    background-color: rgb(158, 158, 158);
    color: rgba(0, 0, 0, 1);
}
.warranty-registration-form .form-fields-part {
    color: rgba(0,0,0,.87);
    padding: 34px 0;
}
.warranty-registration-form .form-top-part {
    margin-bottom: 22px;
}
.warranty-registration-form .warranty-form-title-row {
    padding-left: 34px;
    padding-right: 34px;
}
.warranty-registration-form .warranty-form-top-title {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    font-size: 34px;
    line-height: 135%;
    max-width: 100%;
    min-width: 0%;
    color: rgba(0,0,0,.87);
}
.warranty-registration-form .warranty-form-header-description {
    padding-left: 34px;
    padding-right: 34px;
    white-space: pre-wrap;
    line-height: 135%;
    margin-top: 22px;
    font-size: 13px;
    color: rgba(0,0,0,.87);
}
.warranty-registration-form .form-required-warning {
    padding-left: 34px;
    padding-right: 34px;
    color: #db4437;
    margin-top: 22px;
    font-size: 13px;
}
.warranty-registration-form .form-middle-part {
    padding: 0 17px;
}
.warranty-registration-form .form-field {
    background-color: transparent;
    margin-top: 2px;
    padding: 16px 17px;
    page-break-inside: avoid;
    -webkit-transition: background-color 200ms cubic-bezier(0.0,0.0,0.2,1);
    transition: background-color 200ms cubic-bezier(0.0,0.0,0.2,1);
}
.warranty-registration-form .form-field-title {
    color: #000;
    font-size: 20px;
    line-height: 135%;
    width: 100%;
}
.warranty-registration-form span.required-warn {
    color: #db4437;
}
.warranty-registration-form .form-main-field {
    -webkit-box-align: center;
    box-align: center;
    -webkit-align-items: center;
    align-items: center;
    display: -webkit-box;
    display: -moz-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    box-pack: justify;
    -webkit-justify-content: space-between;
    justify-content: space-between;
    padding: .5em .5em .5em 0;
}
.warranty-registration-form .form-field-inside {
    height: 45px;
    position: relative;
    vertical-align: top;
    width: 50%;
    max-width: 100%;
}
.warranty-registration-form input.form-input-field {
    -webkit-box-flex: 1;
    box-flex: 1;
    -webkit-flex-grow: 1;
    flex-grow: 1;
    -webkit-flex-shrink: 1;
    flex-shrink: 1;
    background-color: transparent;
    display: block;
    font: 400 16px Roboto,RobotoDraft,Helvetica,Arial,sans-serif;
    line-height: 24px;
    margin: 0;
    min-width: 0%;
    outline: none;
    padding: 0;
    z-index: 0;
    font-style: normal !important;
    margin-top: 15px;
	height: 30px !important;
	border: 0;
    border-bottom: 1px solid #e1e1e1;
}
.warranty-registration-form .form-submit.field {
    margin-top: 20px;
    margin-bottom: 20px;
}
.warranty-registration-form .form-submit.field button, .form-submit.field button:hover, .form-submit.field button:focus, .form-submit.field button:active {
	background-color: #4285f4;
    color: #fff;
    text-transform: uppercase;
    border: none;
    border-radius: 3px;
}
.warranty-registration-form .form-bottom-line {
    color: rgba(0,0,0,0.54);
    font: 400 12px Roboto,RobotoDraft,Helvetica,Arial,sans-serif;
    margin-top: 8px;
}
</style>